# SwiftLint configuration for Presenter Overlay

# Paths to exclude
excluded:
  - Pods
  - DerivedData
  - .build

# Rules configuration
disabled_rules:
  - todo  # TODOs are fine during development

opt_in_rules:
  - empty_count
  - closure_spacing

# Identifier name rules - allow x, y for coordinates
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - x
    - y
    - id
    - to

# Line length
line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_comments: true

# Large tuple - allow up to 3 for UI callbacks
large_tuple:
  warning: 4
  error: 5

# File length
file_length:
  warning: 500
  error: 1000

# Type body length
type_body_length:
  warning: 400
  error: 600

# Function body length
function_body_length:
  warning: 60
  error: 100

# Nesting
nesting:
  type_level: 2
  function_level: 3
